In [1]:
import numpy as np

In [29]:
vector = np.arange(-6,6).reshape(3,2,2)

print(vector)
print(vector.shape)

np.reshape(vector, (vector.shape[0],-1))
#X_train = np.reshape(X_train, (X_train.shape[0], -1))

[[[-6 -5]
  [-4 -3]]

 [[-2 -1]
  [ 0  1]]

 [[ 2  3]
  [ 4  5]]]
(3, 2, 2)


array([[-6, -5, -4, -3],
       [-2, -1,  0,  1],
       [ 2,  3,  4,  5]])

In [30]:
print(vector)
np.maximum(vector, 0)

[[[-6 -5]
  [-4 -3]]

 [[-2 -1]
  [ 0  1]]

 [[ 2  3]
  [ 4  5]]]


array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1]],

       [[2, 3],
        [4, 5]]])

In [38]:
salida_relu = np.array([[1,6,4,0],[0,0,3,1]])
print(salida_relu)
np.heaviside(salida_relu, 0).astype(int)

[[1 6 4 0]
 [0 0 3 1]]


array([[1, 1, 1, 0],
       [0, 0, 1, 1]])

In [39]:
dlr = np.heaviside(salida_relu, 0).astype(int) if salida_relu.all() > 0 else 4
print(dlr)

4


In [3]:

thisdict = {
  "a": [1,2,3],
  "b": [1,2,3],
  "c": [1,2,3]
}

thisdict.keys()


dict_keys(['a', 'b', 'c'])

In [5]:
diction = {}

diction["a"] = thisdict["a"]

diction["a"] = 3
print(diction["a"], thisdict["a"])

3 [1, 2, 3]


In [9]:
hidden_dims = [50, 100, 1000]
regs = [0.0, 0.3, 0.7]
lrs = [1e-2, 1e-3, 1e-4]
num_epochs = [10, 20]

grid_search = [
                [hidden_dim, reg, lr, epochs] for hidden_dim in hidden_dims \
                                              for reg in regs \
                                              for lr in lrs \
                                              for epochs in num_epochs
]

print(len(grid_search))
for num, [hidden_dim, reg, lr, epochs] in enumerate(grid_search):
    print(hidden_dim)

54
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000


In [2]:
x = 3
disdic = {}

disdic['W' + str(x)] = 2

print(disdic)

{'W3': 2}


In [7]:
lista = [3,4,1,4]

for entrada, elemento in enumerate(lista, start=1):
    print(entrada, elemento)

1 3
2 4
3 1
4 4


In [10]:
dim = 4
for i in range(dim-1):
    print(i)

0
1
2


In [13]:
dic = {'W1': [1,2,3,4], 'W2': [1,2,3,4]}

In [14]:
print(dic)

{'W1': [1, 2, 3, 4], 'W2': [1, 2, 3, 4]}


In [26]:
np.square(dic['W1'])

array([ 1,  4,  9, 16], dtype=int32)

In [27]:
np.sum(np.square(dic['W1']))

30

In [22]:
print(dic)

{'W1': [1, 2, 3, 4], 'W2': [1, 2, 3, 4]}


In [24]:
W1 = np.array([1,2,3,4])

W1*W1

array([ 1,  4,  9, 16])

In [37]:
lista = np.sum([np.sum(np.square(val)) for item, val in dic.items()])

In [39]:
print(lista)

60


In [31]:
for item, val in dic.items():
    print(item, val)

W1 [1, 2, 3, 4]
W2 [1, 2, 3, 4]


In [42]:
rango = 4

for i in range(rango):
    print(rango - 1 - i)

3
2
1
0


In [46]:
for i in range(rango-1, -1, -1):
    print(i)

3
2
1
0


In [15]:
dout = np.array([[1,2,3],[0,3,1]])

x = np.array([[1,-1,3],[0,-3,1]])

print(dout, '\t')
print(x)


[[1 2 3]
 [0 3 1]] 	
[[ 1 -1  3]
 [ 0 -3  1]]


In [9]:
alpha = 100
dx = dout
dx[x<0] = 0#dout*alpha
print(dx)

[[1 0 3]
 [0 0 1]]


In [10]:


dx = [dout if x>0 else dout*alpha for dout, x in zip(dout, x)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [12]:
for j in zip(dout, x):
    print(j)

(array([1, 0, 3]), array([ 1, -1,  3]))
(array([0, 0, 1]), array([ 0, -3,  1]))


In [16]:
alpha =100
x = np.where(x>0, dout, dout*alpha)
print(x)

[[  1 200   3]
 [  0 300   1]]


In [8]:
matriz = np.array([[1,2,3],[10,11,13]])
print(matriz)
mean = np.mean(matriz, axis=0, keepdims=True)

[[ 1  2  3]
 [10 11 13]]


In [9]:
print(mean)

print(matriz.shape)
print(mean.shape)

[[5.5 6.5 8. ]]
(2, 3)
(1, 3)


In [19]:
x = np.array([3,4,33,5,2])
p=0.9
mask = np.random.rand(*x.shape)< p


In [20]:
x *= mask

In [21]:
x

array([ 3,  4, 33,  5,  2])

In [22]:
np.random.seed(30)
np.random.rand(*x.shape)

array([0.64414354, 0.38074849, 0.66304791, 0.16365073, 0.96260781])

In [25]:
np.random.seed(33)
np.random.rand(*x.shape)

array([0.24851013, 0.44997542, 0.4109408 , 0.26029969, 0.87039569])

In [ ]:
N, C, H, W = 1, 2, 2, 2
sh = (N, C, H, W)

ar = np.arange(0, N*C*H*W)

rsh = np.reshape(ar, sh)

G = 2

rrsh = rsh.transpose(0, 2, 3, 1).reshape(N, H*W, C) # reordeno y primer reshape

dim = C // G 

rrrsh = rrsh.reshape(N*dim, H*W, G)


def reshape_volume(volume, G):
    
    N, C, H, W = volume.shape
    out1 = volume.transpose(0, 2, 3, 1).reshape(N, H*W, C) 
    
    dim = C // G
    out2 = out.reshape(N*dim, H*W, G)
    out3 = out.reshape(N*dim, H*W*G)
    
    print('volume sh 1: ', volume.shape)
    print('volume sh 2: ', out1.shape)
    print('volume sh 3 ', out2.shape)
    print('volume sh 4: ', out3.shape)
    return out3

    
def undo_reshape(volume, G):
    dim = C // G
    
    out1 = volume.reshape(N*dim, H*W, G)
    out2 = out.reshape(N, H*W, C)
    out3 = out.reshape(N, H, W, C).transpose(0, 3, 1, 2)

    print('volume sh 4: ', volume.shape)
    print('volume sh 3: ', out1.shape)
    print('volume sh 2 ', out2.shape)
    print('volume sh 1: ', out3.shape)

    return out3


N, C, H, W = 2, 6, 4, 5
sh = (N, C, H, W)
ar = np.arange(0, N*C*H*W)
rsh = np.reshape(ar, sh)

out = reshape_volume(rsh, G)
print(out.shape)
out = undo_reshape(out, G)


In [ ]:
import torch
assert '.'.join(torch.__version__.split('.')[:2]) == '1.4'

import torch.optim as optim
from torch.utils.data import DataLoader
from torch.utils.data import sampler

import torchvision.datasets as dset
import torchvision.transforms as T

import numpy as np
model = None
optimizer = None

def flatten(x):
    N = x.shape[0] # read in N, C, H, W
    return x.view(N, -1)  # "flatten" the C * H * W values into a single vector per image

# *****START OF YOUR CODE (DO NOT DELETE/MODIFY THIS LINE)*****
class Flatten(nn.Module):
    def forward(self, x):
        return flatten(x)

# Primera red de prueba de la sugerencia:
#[conv-relu-pool]xN -> [affine]xM -> [softmax or SVM]

in_channel = 3
num_classes = 10
channel_1 = 100

import torch.nn as nn
model = nn.Sequential(
    nn.Conv2d(in_channel, channel_1, kernel_size=5, padding=2, bias=True),
    nn.BatchNorm2d(num_features=channel_1),
    nn.MaxPool2d(kernel_size=2)
)

from torchsummary import summary
summary(model, (3,200,200))

In [4]:
# Increment items 0 and 1, and increment item 2 twice:
a = np.array([1, 2, 3, 4])
np.add.at(a, [0, 1, 2, 2], 3)
a

array([4, 5, 9, 4])

In [6]:
a = np.array([[1,2,3],
              [1,2,3]])

b = np.array([[3,3,3],
              [5,0,5]])

print(a - b)
np.sum(np.square(a - b))

[[-2 -1  0]
 [-4  2 -2]]


29

In [7]:
import torch

In [16]:
a = torch.tensor([[[1,1], [2,2]], [[1,1], [2,2]]])
b = torch.tensor([[[3,3], [4,4]], [[3,3], [4,4]]])

print(a, b)
print(torch.sum(a[:, 1, : ] * b[:, 1, : ], dim =1) )

tensor([[[1, 1],
         [2, 2]],

        [[1, 1],
         [2, 2]]]) tensor([[[3, 3],
         [4, 4]],

        [[3, 3],
         [4, 4]]])
tensor([16, 16])


In [ ]:
torch.transpose()