In [1]:
import numpy as np

In [29]:
vector = np.arange(-6,6).reshape(3,2,2)

print(vector)
print(vector.shape)

np.reshape(vector, (vector.shape[0],-1))
#X_train = np.reshape(X_train, (X_train.shape[0], -1))

[[[-6 -5]
  [-4 -3]]

 [[-2 -1]
  [ 0  1]]

 [[ 2  3]
  [ 4  5]]]
(3, 2, 2)


array([[-6, -5, -4, -3],
       [-2, -1,  0,  1],
       [ 2,  3,  4,  5]])

In [30]:
print(vector)
np.maximum(vector, 0)

[[[-6 -5]
  [-4 -3]]

 [[-2 -1]
  [ 0  1]]

 [[ 2  3]
  [ 4  5]]]


array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1]],

       [[2, 3],
        [4, 5]]])

In [38]:
salida_relu = np.array([[1,6,4,0],[0,0,3,1]])
print(salida_relu)
np.heaviside(salida_relu, 0).astype(int)

[[1 6 4 0]
 [0 0 3 1]]


array([[1, 1, 1, 0],
       [0, 0, 1, 1]])

In [39]:
dlr = np.heaviside(salida_relu, 0).astype(int) if salida_relu.all() > 0 else 4
print(dlr)

4


In [3]:

thisdict = {
  "a": [1,2,3],
  "b": [1,2,3],
  "c": [1,2,3]
}

thisdict.keys()


dict_keys(['a', 'b', 'c'])

In [5]:
diction = {}

diction["a"] = thisdict["a"]

diction["a"] = 3
print(diction["a"], thisdict["a"])

3 [1, 2, 3]


In [9]:
hidden_dims = [50, 100, 1000]
regs = [0.0, 0.3, 0.7]
lrs = [1e-2, 1e-3, 1e-4]
num_epochs = [10, 20]

grid_search = [
                [hidden_dim, reg, lr, epochs] for hidden_dim in hidden_dims \
                                              for reg in regs \
                                              for lr in lrs \
                                              for epochs in num_epochs
]

print(len(grid_search))
for num, [hidden_dim, reg, lr, epochs] in enumerate(grid_search):
    print(hidden_dim)

54
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
50
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000
1000


In [2]:
x = 3
disdic = {}

disdic['W' + str(x)] = 2

print(disdic)

{'W3': 2}


In [7]:
lista = [3,4,1,4]

for entrada, elemento in enumerate(lista, start=1):
    print(entrada, elemento)

1 3
2 4
3 1
4 4


In [10]:
dim = 4
for i in range(dim-1):
    print(i)

0
1
2


In [13]:
dic = {'W1': [1,2,3,4], 'W2': [1,2,3,4]}

In [14]:
print(dic)

{'W1': [1, 2, 3, 4], 'W2': [1, 2, 3, 4]}


In [26]:
np.square(dic['W1'])

array([ 1,  4,  9, 16], dtype=int32)

In [27]:
np.sum(np.square(dic['W1']))

30

In [22]:
print(dic)

{'W1': [1, 2, 3, 4], 'W2': [1, 2, 3, 4]}


In [24]:
W1 = np.array([1,2,3,4])

W1*W1

array([ 1,  4,  9, 16])

In [37]:
lista = np.sum([np.sum(np.square(val)) for item, val in dic.items()])

In [39]:
print(lista)

60


In [31]:
for item, val in dic.items():
    print(item, val)

W1 [1, 2, 3, 4]
W2 [1, 2, 3, 4]


In [42]:
rango = 4

for i in range(rango):
    print(rango - 1 - i)

3
2
1
0


In [46]:
for i in range(rango-1, -1, -1):
    print(i)

3
2
1
0


In [15]:
dout = np.array([[1,2,3],[0,3,1]])

x = np.array([[1,-1,3],[0,-3,1]])

print(dout, '\t')
print(x)


[[1 2 3]
 [0 3 1]] 	
[[ 1 -1  3]
 [ 0 -3  1]]


In [9]:
alpha = 100
dx = dout
dx[x<0] = 0#dout*alpha
print(dx)

[[1 0 3]
 [0 0 1]]


In [10]:


dx = [dout if x>0 else dout*alpha for dout, x in zip(dout, x)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [12]:
for j in zip(dout, x):
    print(j)

(array([1, 0, 3]), array([ 1, -1,  3]))
(array([0, 0, 1]), array([ 0, -3,  1]))


In [16]:
alpha =100
x = np.where(x>0, dout, dout*alpha)
print(x)

[[  1 200   3]
 [  0 300   1]]


In [8]:
matriz = np.array([[1,2,3],[10,11,13]])
print(matriz)
mean = np.mean(matriz, axis=0, keepdims=True)

[[ 1  2  3]
 [10 11 13]]


In [9]:
print(mean)

print(matriz.shape)
print(mean.shape)

[[5.5 6.5 8. ]]
(2, 3)
(1, 3)
