In [1]:
import numpy as np

In [29]:
vector = np.arange(-6,6).reshape(3,2,2)

print(vector)
print(vector.shape)

np.reshape(vector, (vector.shape[0],-1))
#X_train = np.reshape(X_train, (X_train.shape[0], -1))

[[[-6 -5]
  [-4 -3]]

 [[-2 -1]
  [ 0  1]]

 [[ 2  3]
  [ 4  5]]]
(3, 2, 2)


array([[-6, -5, -4, -3],
       [-2, -1,  0,  1],
       [ 2,  3,  4,  5]])

In [30]:
print(vector)
np.maximum(vector, 0)

[[[-6 -5]
  [-4 -3]]

 [[-2 -1]
  [ 0  1]]

 [[ 2  3]
  [ 4  5]]]


array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1]],

       [[2, 3],
        [4, 5]]])

In [38]:
salida_relu = np.array([[1,6,4,0],[0,0,3,1]])
print(salida_relu)
np.heaviside(salida_relu, 0).astype(int)

[[1 6 4 0]
 [0 0 3 1]]


array([[1, 1, 1, 0],
       [0, 0, 1, 1]])

In [39]:
dlr = np.heaviside(salida_relu, 0).astype(int) if salida_relu.all() > 0 else 4
print(dlr)

4
